CREATE DATABASE COFFEECAKE;

CREATE TABLE users(
    ID INT(10) NOT NULL AUTO_INCREAMENT,
    USERNAME VARCHAR(255),
    NAME VARCHAR(255),
    PHONE CHAR(10),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    REPASSWORD VARCHAR (255),
    ADDRESS VARCHAR (255),
    PRIMARY KEY (ID)
)   ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

CREATE TABLE typeproduct(
    IDTYPE INT(10) NOT NULL AUTO_INCREAMENT,
    NAMETYPE VARCHAR (255),
    PRIMARY KEY (IDTYPE)
)

CREATE TABLE product(
    IDPR INT(10) NOT NULL AUTO_INCREAMENT,
    NAMEPR VARCHAR (255),
    IMAGE CHAR (100),
    PRICE INT (10),
    DESCRIPTION VARCHAR (1000),
    IDTYPE INT (10),
    PRIMARY KEY (IDPR)
)

CREATE TABLE bill(
    IDBILL INT (10) NOT NULL AUTO_INCREAMENT,
    USERNAME VARCHAR (255),
    NAME VARCHAR (255),
    PHONE CHAR (15),
    ADDRESS VARCHAR (255),
    NOTE VARCHAR (255),
    IDPR INT (10),
    QUANTUM INT (10),
    PRICE CHAR (50),
    STATUS VARCHAR (100),
    PRIMARY KEY (IDBILL)
)

ALTER TABLE product
ADD FOREIGN KEY (IDTYPE) REFERENCES typeproduct(IDTYPE);

ALTER TABLE bill
ADD FOREIGN KEY (IDPR) REFERENCES product(IDPR)