CREATE DATABASE COFFEECAKE;

CREATE TABLE users(
    ID INT(10) NOT NULL AUTO_INCREAMENT,
    USERNAME VARCHAR(255),
    NAME VARCHAR(255),
    PHONE CHAR(10),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    REPASSWORD VARCHAR (255),
    PRIMARY KEY (ID)
)   ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

CREATE TABLE typeproduct(
    IDTYPE INT(10) NOT NULL AUTO_INCREAMENT,
    NAMETYPE VARCHAR (255),
    PRIMARY KEY (IDTYPE)
)

CREATE TABLE product(
    IDPR INT(10) NOT NULL AUTO_INCREAMENT,
    NAMEPR VARCHAR (255),
    IMAGE CHAR (100),
    PRICE INT (10),
    DESCRIPTION VARCHAR (1000),
    IDTYPE INT (10),
    PRIMARY KEY (IDPR)
)

ALTER TABLE product
ADD FOREIGN KEY (IDTYPE) REFERENCES typeproduct(IDTYPE)